### PR TITLE
Added macOS Mojave compatibility

### PR DESCRIPTION
**Pull request by athlonreg**
- Added macOS Mojave compatibility
- Lilu.kext updated to 1.2.4

### CODE REVIEW

**Comment by athlonreg** [comment]
@dedicahyadi My ar9565 is working for 10.14beta6，maybe you can try to rebuild caches´◡`

**Comment by dedicahyadi** [comment]
i've already did it, push airport40 and also rebuild kextcache. oke maybe will try again later.

**Comment by dedicahyadi** [comment]
ok, thanks a lot. after rebuild kextcache and repair permission, it's works

**Comment by leonardoprc** [comment]
Where do I download "kext for 10.14b5"?

**Comment by athlonreg** [comment]
> Where do I download "kext for 10.14b5"?

You can clone the code from bellow link and build by xcode, then put the lilu and ath9kfixup to clover, then put ath9kinjector to sle, and rebuild cache, repair permissions

**Comment by jianzhao0806** [comment]
oh,I find it could not work on 10.14.1, can you drive it ?

**Comment by Dexter61** [comment]
I have AR9462 but its not working with that kext on Mojave. Anybody have any idea

**Comment by johnnywolinger** [comment]
The provided kext won't fix the wifi scan in some AR9565, including DELL variation, only got activation, but not possible to scan Wifi and connect to the network, what chunnann or anybody need to got data of this card not scanning network, to implement in kext a possible fix?

**Comment by littlekign** [comment]
i have a ar9462 on mojave (version 10.14.5), followed your guide, but i did't work, 
on my mac console show the info: macSysMon: ### WiFiManagerClientCopyDevices failed: NULL.
what should i do?

**Comment by marcosperalta** [comment]
> > Where do I download "kext for 10.14b5"?
> 
> You can clone the code from bellow link and build by xcode, then put the lilu and ath9kfixup to clover, then put ath9kinjector to sle, and rebuild cache, repair permissions
> 
> https://github.com/athlonreg/ATH9KFixup

Hi, sorry but what do you mean when say 'put the lily and ath9fixup to clover'? You mean in EFI/CLOVER/kexts ?  Thanks!

**Comment by marcosperalta** [comment]
Men It works on Mojave 10.14.6 (18G103). Many thanks! Atheros AR9462.

**Pull request closed without merging**
